#!/usr/bin/env bash

alias rmimages='docker rmi $(docker images -q)'
alias rmcontainers='docker rm $(docker ps -a -q)'
alias dbt=docker_build_and_tag

docker_build_and_tag() {
	docker build -t $1 .
}

stop_containers() {
	running_containers=$(docker ps -q | xargs docker inspect -f '{{ .Id }} {{ .Name }}' | grep -v '%patternToSkip%' | awk '{ print $1 }')
	if [[ -n "$running_containers" ]]
	then
		echo Stopping running containers: ${running_containers}
		docker stop ${running_containers}
	fi
}
