#!/usr/bin/env bash

alias gs='git status -sb'
compdef _git gs=git-status
alias gl='git log --oneline --graph --decorate --date=relative'
alias gla='gl --all'
alias rmremote='git push origin --delete'
alias uncommit='git reset --soft HEAD~1'
alias cd-root='cd $(git rev-parse --show-toplevel)'

function push-branch() {
  branch_name=$(git rev-parse --abbrev-ref HEAD)
  git push -u origin ${branch_name}
}
