#!/usr/bin/env bash

# Preferred editor for local and remote sessions
export EDITOR='code --wait'

alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias watch="watch --color "
alias please='sudo $(fc -ln -1)'
alias ssh_add_all='find ~/.ssh -type f -exec grep -l "PRIVATE" {} \; | xargs ssh-add &> /dev/null'

function mktouch() {
	sudo mkdir -p $(dirname $1)
	sudo touch $1
}


# Brew installed https://github.com/wting/autojump
[[ -f /usr/local/etc/profile.d/autojump.sh ]] && . /usr/local/etc/profile.d/autojump.sh
